spring:
  application:
    name: edge-server-${spring.profiles.active:local}
zuul:
  ignoredServices: '*'
  routes:
    webapp:
      path: /webapp/**
      serviceId: webapp
maintenance:
  global:
    enabled: true
eureka:
  client:
    fetchRegistry: true
logging:
  level:
    com.netflix.client: DEBUG
    org.springframework.cloud.netflix: DEBUG
